# Pure instance parameters
`IPRoz( L                 ,1.0e-5                                   ,"m"                                     ,"Length" )
`IPRoz( W                 ,1.0e-5                                   ,"m"                                     ,"Total width including fingers" )
NF = 1                   # Number of fingers, range (1, inf), unit ""
`IPRcz( NRS               ,1.0                                      ,""                                      ,"Number of squares in source" )
`IPRcz( NRD               ,1.0                                      ,""                                      ,"Number of squares in drain" )
`IPRnb( VFBSDOFF          ,0.0                                      ,"V"                                     ,"Flatband voltage offset parameter" )
`IPIcc( MINZ              ,0                                        ,""            ,0           ,1           ,"Minimize either drain or source" )
`IPIcc( RGATEMOD          ,0                                        ,""            ,0           ,3           ,"Gate resistance model selector" )
`IPIcc( RBODYMOD          ,0                                        ,""            ,0           ,2           ,"Distributed body R model" )
`IPIcc( GEOMOD            ,0                                        ,""            ,0           ,10          ,"Geometry-dependent parasitics model" )
`IPIcc( RGEOMOD           ,0                                        ,""            ,0           ,8           ,"Geometry-dependent source/drain resistance,  0: RSH-based, 1: Holistic" )
`IPRcz( RBPB              ,50.0                                     ,"ohm"                                   ,"Resistance between bNodePrime and bNode" )
`IPRcz( RBPD              ,50.0                                     ,"ohm"                                   ,"Resistance between bNodePrime and bNode" )
`IPRcz( RBPS              ,50.0                                     ,"ohm"                                   ,"Resistance between bNodePrime and sbNode" )
`IPRcz( RBDB              ,50.0                                     ,"ohm"                                   ,"Resistance between bNode and dbNode" )
`IPRcz( RBSB              ,50.0                                     ,"ohm"                                   ,"Resistance between bNode and sbNode" )
`IPRnb( SA                ,0.0                                      ,"m"                                     ,"Distance between OD edge from poly from one side" )
`IPRnb( SB                ,0.0                                      ,"m"                                     ,"Distance between OD edge from poly from other side" )
`IPRnb( SD                ,0.0                                      ,"m"                                     ,"Distance between neighboring fingers" )
`IPRoo( SCA               ,0.0                                      ,""            ,-inf        ,inf         ,"Integral of the first distribution function for scattered well dopants" )
`IPRoo( SCB               ,0.0                                      ,""            ,-inf        ,inf         ,"Integral of second distribution function for scattered well dopants" )
`IPRoo( SCC               ,0.0                                      ,""            ,-inf        ,inf         ,"Integral of third distribution function for scattered well dopants" )
`IPRoo( SC                ,0.0                                      ,"m"           ,-inf        ,inf         ,"Distance to a single well edge; if <= 0.0, turn off WPE" )
`IPRcz( AS                ,0.0                                      ,"m^2"                                   ,"Source-to-substrate junction area" )
`IPRcz( AD                ,0.0                                      ,"m^2"                                   ,"Drain-to-substrate junction area" )
`IPRcz( PS                ,0.0                                      ,"m"                                     ,"Source-to-substrate junction perimeter" )
`IPRcz( PD                ,0.0                                      ,"m"                                     ,"Drain-to-substrate junction perimeter" )

# Both model and instance parameters
XGW = 0.0                # Distance from gate contact center to device edge, unit "m"
NGCON = 1                # Number of gate contacts, range (1, 2), unit ""
DTEMP = 0.0              # Offset of device temperature, unit "K"
MULU0 = 1.0              # Multiplication factor for low field mobility, unit "m^2/(V*s)"
DELVTO = 0.0             # Zero bias threshold voltage variation, unit "V"
IDS0MULT = 1.0           # Variability in drain current for miscellaneous reasons, unit ""
EDGEFET = 0              # 0: Edge FET Model OFF, 1: Edge FET Model ON, range (0, 1), unit ""
SSLMOD = 0               # Sub-surface leakage drain current, 0: Turn off  1: Turn on, range (0, 1), unit ""

# Pure model parameters
`MPIty( TYPE              ,`ntype                                   ,""                                      ,"N-type = 1, P-type = -1" )
CVMOD = 0                # 0: Consistent I-V/C-V, 1: Different I-V/C-V, range (0, 1), unit 
COVMOD = 0               # 0: Use bias-independent overlap capacitances,  1: Use bias-dependent overlap capacitances, range (0, 1), unit 
RDSMOD = 0               # 0: Internal bias dependent and external bias independent S/D resistance model, 1: External S/D resistance model, 2: Internal S/D resistance model, range (0, 2), unit 
WPEMOD = 0               # Model flag, range (0, 1), unit 
ASYMMOD = 0              # 0: Asymmetry model turned off - forward mode parameters used,  1: Asymmetry model turned on, range (0, 1), unit 
GIDLMOD = 0              # 0: Turn off GIDL current,  1: Turn on GIDL current, range (0, 1), unit 
IGCMOD = 0               # 0: Turn off Igc, Igs and Igd, 1: Turn on Igc, Igs and Igd, range (0, 1), unit 
IGBMOD = 0               # 0: Turn off Igb, 1: Turn on Igb, range (0, 1), unit 
TNOIMOD = 0              # Thermal noise model selector, range (0, 1), unit 
SHMOD = 0                # 0: Self heating model OFF, 1: Self heating model ON, range (0, 1), unit 
MOBSCALE = 0             # Mobility scaling model, 0: Old Model,  1: New Model, range (0, 1), unit 

# Device parameters
LLONG = 0               # Mobility scaling model, 0: Old Model,  1: New Model, unit 
LMLT = 0                # Mobility scaling model, 0: Old Model,  1: New Model, unit 
WMLT = 0                # Mobility scaling model, 0: Old Model,  1: New Model, unit 
XL = 0.0                 # L offset for channel length due to mask/etch effect, unit "m"
WWIDE = 0.0             # L offset for channel length due to mask/etch effect, unit "m"
XW = 0.0                 # W offset for channel width due to mask/etch effect, unit "m"
LINT = 0.0               # Delta L for I-V, unit "m"
LL = 0.0                 # Length reduction parameter, unit "m^(1+LLN)"
LW = 0.0                 # Length reduction parameter, unit "m^(1+LWN)"
LWL = 0.0                # Length reduction parameter, unit "m^(1+LLN+LWN)"
LLN = 1.0                # Length reduction parameter, unit ""
LWN = 1.0                # Length reduction parameter, unit ""
WINT = 0.0               # Delta W for I-V, unit "m"
WL = 0.0                 # Width reduction parameter, unit "m^(1+WLN)"
WW = 0.0                 # Width reduction parameter, unit "m^(1+WWN)"
WWL = 0.0                # Width reduction parameter, unit "m^(1+WWN+WLN)"
WLN = 1.0                # Width reduction parameter, unit ""
WWN = 1.0                # Width reduction parameter, unit ""
DLC = 0.0                # Delta L for C-V, unit "m"
LLC = 0.0                # Length reduction parameter, unit "m^(1+LLN)"
LWC = 0.0                # Length reduction parameter, unit "m^(1+LWN)"
LWLC = 0.0               # Length reduction parameter, unit "m^(1+LWN+LLN)"
DWC = 0.0                # Delta W for C-V, unit "m"
WLC = 0.0                # Width reduction parameter, unit "m^(1+WLN)"
WWC = 0.0                # Width reduction parameter, unit "m^(1+WWN)"
WWLC = 0.0               # Width reduction parameter, unit "m^(1+WWN+WLN)"
TOXE = 3.0e-9            # Effective gate dielectric thickness relative to SiO2, range (0.0, inf), unit "m"
TOXP = TOXE              # Physical gate dielectric thickness. If not given, TOXP is calculated from TOXE and DTOX, range (0.0, inf), unit "m"
DTOX = 0.0               # Difference between effective dielectric thickness, unit "m"
NDEP = 1e24              # Channel doping concentration for I-V, unit "1/m^3"
NDEPL1 = 0.0             # Length dependence coefficient of NDEP, unit "m"
NDEPLEXP1 = 0.0         # Length dependence coefficient of NDEP, unit "m"
NDEPL2 = 0.0             # Length dependence of NDEP - For Short Channel Devices, unit "m"
NDEPLEXP2 = 0.0         # Length dependence of NDEP - For Short Channel Devices, unit "m"
NDEPW = 0.0              # Width dependence coefficient of NDEP, unit "m"
NDEPWEXP = 0.0          # Width dependence coefficient of NDEP, unit "m"
NDEPWL = 0.0             # Width-length dependence coefficient of NDEP, unit "m^2"
NDEPWLEXP = 0.0         # Width-length dependence coefficient of NDEP, unit "m^2"
LNDEP = 0.0              # Length dependence of NDEP, unit "1/m^2"
WNDEP = 0.0              # Width dependence of NDEP, unit "1/m^2"
PNDEP = 0.0              # Area dependence of NDEP , unit "1/m"
NDEPCV = 1e24            # Channel doping concentration for C-V, unit "1/m^3"
NDEPCVL1 = 0.0           # Length dependence coefficient of NDEPCV, unit "m"
NDEPCVLEXP1 = 0.0       # Length dependence coefficient of NDEPCV, unit "m"
NDEPCVL2 = 0.0           # Length dependence coefficient of NDEPCV - For Short Channel Devices, unit "m"
NDEPCVLEXP2 = 0.0       # Length dependence coefficient of NDEPCV - For Short Channel Devices, unit "m"
NDEPCVW = 0.0            # Width dependence coefficient of NDEPCV, unit "m"
NDEPCVWEXP = 0.0        # Width dependence coefficient of NDEPCV, unit "m"
NDEPCVWL = 0.0           # Width-length dependence coefficient of NDEPCV, unit "m^2"
NDEPCVWLEXP = 0.0       # Width-length dependence coefficient of NDEPCV, unit "m^2"
LNDEPCV = 0.0            # Length dependence  of NDEP for C-V, unit "1/m^2"
WNDEPCV = 0.0            # Width dependence of NDEP for C-V, unit "1/m^2"
PNDEPCV = 0.0            # Area dependence of NDEP for C-V, unit "1/m"
NGATE = 5e25             # Gate doping concentration, unit "1/m^3"
LNGATE = 0.0             # Length dependence of NGATE, unit "1/m^2"
WNGATE = 0.0             # Width dependence of NGATE, unit "1/m^2"
PNGATE = 0.0             # Area dependence of NGATE, unit "1/m"
EASUB = 4.05             # Electron affinity of substrate, unit "eV"
NI0SUB = 4.05           # Electron affinity of substrate, unit "eV"
BG0SUB = 1.17            # Bandgap of substrate at 300.15K, range (0.0, inf), unit "eV"
EPSRSUB = 11.9           # Relative dielectric constant of the channel material, range (0.0, inf), unit ""
EPSROX = 3.9             # Relative dielectric constant of the gate dielectric, range (0.0, inf), unit ""
XJ = 1.5e-7              # S/D junction depth, unit "m"
LXJ = 0.0                # Length dependence of XJ, unit "m^2"
WXJ = 0.0                # Width dependence of XJ, unit "m^2"
PXJ = 0.0                # Area dependence of XJ, unit "m^3"
VFB = -0.5               # Flatband voltage, unit "V"
LVFB = 0.0               # Length dependence of VFB, unit "V*m"
WVFB = 0.0               # Width dependence of VFB, unit "V*m"
PVFB = 0.0               # Area dependence of VFB, unit "V*m^2"
VFBCV = -0.5             # Flatband voltage for C-V, unit "V"
LVFBCV = 0.0             # Length dependence of VFBCV, unit "V*m"
WVFBCV = 0.0             # Width dependence of VFBCV, unit "V*m"
PVFBCV = 0.0             # Area dependence of VFBCV, unit "V*m^2"
VFBCVL = 0.0             # Length dependence coefficient of VFBCV, unit "m"
VFBCVLEXP = 0.0         # Length dependence coefficient of VFBCV, unit "m"
VFBCVW = 0.0             # Width dependence coefficient of VFBCV, unit "m"
VFBCVWEXP = 0.0         # Width dependence coefficient of VFBCV, unit "m"
VFBCVWL = 0.0            # Width-length dependence coefficient of VFBCV, unit "m^2"
VFBCVWLEXP = 0.0        # Width-length dependence coefficient of VFBCV, unit "m^2"
DELVFBACC = 0.0          # VFB shift in the accumulation region, valid for CVMOD=1 only, unit ""

# Diode parameters
PERMOD = 1               # Whether PS/PD (when given) include gate-edge perimeter, range (0, 1), unit 
DWJ = DWC                # Delta W for S/D junctions, unit "m"

# Short channel effects
NSD = 1e26               # S/D doping concentration, unit "1/m^3"
LNSD = 0.0               # Length dependence of NSD, unit "1/m^2"
WNSD = 0.0               # Width dependence of NSD, unit "1/m^2"
PNSD = 0.0               # Area dependence of NSD, unit "1/m"
DVTP0 = 0.0              # DITS, unit "m"
LDVTP0 = 0               # Length dependence of DVTP0, unit "m^2"
WDVTP0 = 0               # Width dependence of DVTP0, unit "m^2"
PDVTP0 = 0               # Area dependence of DVTP0, unit "m^3"
DVTP1 = 0.0              # DITS, unit "1/V"
LDVTP1 = 0               # Length dependence of DVTP1, unit "m/V"
WDVTP1 = 0               # Width dependence of DVTP1, unit "m/V"
PDVTP1 = 0               # Area dependence of DVTP1, unit "m^2/V"
DVTP2 = 0.0              # DITS, unit "m*V"
LDVTP2 = 0               # Length dependence of DVTP2, unit "m^2/V"
WDVTP2 = 0               # Width dependence of DVTP2, unit "m^2/V"
PDVTP2 = 0               # Area dependence of DVTP2, unit "m^3/V"
DVTP3 = 0.0              # DITS, unit ""
LDVTP3 = 0               # Length dependence of DVTP3, unit "m"
WDVTP3 = 0               # Width dependence of DVTP3, unit "m"
PDVTP3 = 0               # Area dependence of DVTP3, unit "m^2"
DVTP4 = 0.0              # DITS, unit "1/V"
LDVTP4 = 0               # Length dependence of DVTP4, unit "m/V"
WDVTP4 = 0               # Width dependence of DVTP4, unit "m/V"
PDVTP4 = 0               # Area dependence of DVTP4, unit "m^2/V"
DVTP5 = 0.0              # DITS, unit "V"
LDVTP5 = 0               # Length dependence of DVTP5, unit "m*V"
WDVTP5 = 0               # Width dependence of DVTP5, unit "m*V"
PDVTP5 = 0               # Area dependence of DVTP5, unit "m^2*V"
PHIN = 0.045             # Non-uniform vertical doping effect on surface potential, unit "V"
LPHIN = 0.0              # Length dependence of PHIN, unit "m*V"
WPHIN = 0.0              # Width dependence of PHIN, unit "m*V"
PPHIN = 0.0              # Area dependence of PHIN, unit "m^2*V"
ETA0 = 0.08              # DIBL coefficient, unit ""
LETA0 = 0.0              # Length dependence of ETA0, unit "m"
WETA0 = 0.0              # Width dependence of ETA0, unit "m"
PETA0 = 0.0              # Area dependence of ETA0, unit "m^2"
ETA0R = ETA0             # DIBL coefficient, unit ""
LETA0R = LETA0           # Length dependence of ETA0R, unit "m"
WETA0R = WETA0           # Width dependence of ETA0R, unit "m"
PETA0R = PETA0           # Area dependence of ETA0R, unit "m^2"
DSUB = 1.0               # Length scaling exponent for DIBL, unit ""
ETAB = -0.07             # Body bias coefficient for subthreshold DIBL effect, unit "1/V"
ETABEXP = -0.07         # Body bias coefficient for subthreshold DIBL effect, unit "1/V"
LETAB = 0.0              # Length dependence of ETAB, unit "m/V"
WETAB = 0.0              # Width dependence of ETAB, unit "m/V"
PETAB = 0.0              # Area dependence of ETAB, unit "m^2/V"
K1 = 0.0                 # First-order body-bias Vth shift due to vertical non-uniform doping, unit "V^0.5"
K1L = 0.0                # length dependence coefficient of K1, unit ""
K1LEXP = 0.0            # length dependence coefficient of K1, unit ""
K1W = 0.0                # Width dependence coefficient of K1, unit ""
K1WEXP = 0.0            # Width dependence coefficient of K1, unit ""
K1WL = 0.0               # Width-length dependence coefficient of K1, unit ""
K1WLEXP = 0.0           # Width-length dependence coefficient of K1, unit ""
LK1 = 0.0                # Length dependence of K1, unit "m*V^0.5"
WK1 = 0.0                # Width dependence of K1, unit "m*V^0.5"
PK1 = 0.0                # Area dependence of K1, unit "m^2*V^0.5"
K2 = 0.0                 # Vth shift due to vertical non-uniform doping, unit "V"
K2L = 0.0                # Length dependence coefficient of K2, unit "m^K2LEXP"
K2LEXP = 0.0            # Length dependence coefficient of K2, unit "m^K2LEXP"
K2W = 0.0                # Width dependence coefficient of K2, unit "m^K2WEXP"
K2WEXP = 0.0            # Width dependence coefficient of K2, unit "m^K2WEXP"
K2WL = 0.0               # Width-length dependence coefficient of K2, unit "m^(2*K2WLEXP)"
K2WLEXP = 0.0           # Width-length dependence coefficient of K2, unit "m^(2*K2WLEXP)"
LK2 = 0.0                # Length dependence of K2, unit "m"
WK2 = 0.0                # Width dependence of K2, unit "m"
PK2 = 0.0                # Area dependence of K2, unit "m^2"

# Quantum mechanical effects
ADOS = 0.0               # Quantum mechanical effect pre-factor switch in inversion, unit ""
BDOS = 1.0               # Charge centroid parameter - slope of C-V curve under QME in inversion, unit ""
QM0 = 1.0               # Charge centroid parameter - slope of C-V curve under QME in inversion, unit ""
ETAQM = 0.54             # Bulk charge coefficient for charge centroid in inversion, unit ""

# Sub-threshold swing factor
CIT = 0.0                # Parameter for interface traps, unit "F/m^2"
LCIT = 0.0               # Length dependence of CIT, unit "F/m"
WCIT = 0.0               # Width dependence of CIT, unit "F/m"
PCIT = 0.0               # Area dependence of CIT, unit "F"
NFACTOR = 0.0            # Subthreshold slope factor, unit ""
NFACTORL = 0.0           # Length dependence coefficient of NFACTOR, unit "m^NFACTORLEXP"
NFACTORLEXP = 0.0       # Length dependence coefficient of NFACTOR, unit "m^NFACTORLEXP"
NFACTORW = 0.0           # Width dependence coefficient of NFACTOR, unit "m^NFACTORWEXP"
NFACTORWEXP = 0.0       # Width dependence coefficient of NFACTOR, unit "m^NFACTORWEXP"
NFACTORWL = 0.0          # Width-length dependence coefficient of NFACTOR, unit "m^(2*NFACTORWLEXP)"
NFACTORWLEXP = 0.0      # Width-length dependence coefficient of NFACTOR, unit "m^(2*NFACTORWLEXP)"
LNFACTOR = 0.0           # Length dependence of NFACTOR, unit "m"
WNFACTOR = 0.0           # Width dependence of NFACTOR, unit "m"
PNFACTOR = 0.0           # Area dependence of NFACTOR, unit "m^2"
CDSCD = 1e-9             # Drain bias sensitivity of subthreshold slope, unit "F/m^2/V"
CDSCDL = 0.0             # Length dependence coefficient of CDSCD, unit "m^CDSCDLEXP"
CDSCDLEXP = 0.0         # Length dependence coefficient of CDSCD, unit "m^CDSCDLEXP"
LCDSCD = 0.0             # Length dependence of CDSCD, unit "F/m/V"
WCDSCD = 0.0             # Width dependence of CDSCD, unit "F/m/V"
PCDSCD = 0.0             # Area dependence of CDSCD, unit "F/V"
CDSCDR = CDSCD           # Drain bias sensitivity of subthreshold slope, unit "F/m^2/V"
CDSCDLR = CDSCDL         # Length dependence coefficient of CDSCD, unit "m^CDSCDLEXP"
LCDSCDR = LCDSCD         # Length dependence of CDSCDR, unit "F/m/V"
WCDSCDR = WCDSCD         # Width dependence of CDSCDR, unit "F/m/V"
PCDSCDR = PCDSCD         # Area dependence of CDSCDR, unit "F/V"
CDSCB = 0.0              # Body-bias sensitivity of subthreshold slope, unit "F/m^2/V"
CDSCBL = 0.0             # Length dependence coefficient of CDSCB, unit "m^CDSCBLEXP"
CDSCBLEXP = 0.0         # Length dependence coefficient of CDSCB, unit "m^CDSCBLEXP"
LCDSCB = 0.0             # Length dependence of CDSCB, unit "F/m/V"
WCDSCB = 0.0             # Width dependence of CDSCB, unit "F/m/V"
PCDSCB = 0.0             # Area dependence of CDSCB, unit "F/V"

# Drain saturation voltage
VSAT = 1e5               # Saturation velocity, unit "m/s"
LVSAT = 0.0              # Length dependence of VSAT, unit "m^2/s"
WVSAT = 0.0              # Width dependence of VSAT, unit "m^2/s"
PVSAT = 0.0              # Area dependence of VSAT, unit "m^3/s"
VSATL = 0.0              # Length dependence coefficient of VSAT, unit "m^VSATLEXP"
VSATLEXP = 0.0          # Length dependence coefficient of VSAT, unit "m^VSATLEXP"
VSATW = 0.0              # Width dependence coefficient of VSAT, unit "m^VSATWEXP"
VSATWEXP = 0.0          # Width dependence coefficient of VSAT, unit "m^VSATWEXP"
VSATWL = 0.0             # Width-length dependence coefficient of VSAT, unit "m^(2*VSATWLEXP)"
VSATWLEXP = 0.0         # Width-length dependence coefficient of VSAT, unit "m^(2*VSATWLEXP)"
VSATR = VSAT             # Saturation velocity, unit "m/s"
LVSATR = LVSAT           # Length dependence of VSATR, unit "m^2/s"
WVSATR = WVSAT           # Width dependence of VSATR, unit "m^2/s"
PVSATR = PVSAT           # Area dependence of VSATR, unit "m^3/s"
DELTA = 0.125            # Smoothing function factor for Vdsat, unit ""
LDELTA = 0.0             # Length dependence of DELTA, unit "m"
WDELTA = 0.0             # Width dependence of DELTA, unit "m"
PDELTA = 0.0             # Area dependence of DELTA, unit "m^2"
DELTAL = 0.0             # Length dependence coefficient of DELTA, unit "m^DELTALEXP"
DELTALEXP = 0.0         # Length dependence coefficient of DELTA, unit "m^DELTALEXP"
VSATCV = 1e5             # VSAT parameter for C-V, unit "m/s"
LVSATCV = 0.0            # Length dependence of VSATCV, unit "m^2/s"
WVSATCV = 0.0            # Width dependence of VSATCV, unit "m^2/s"
PVSATCV = 0.0            # Area dependence of VSATCV, unit "m^3/s"
VSATCVL = 0.0            # Length dependence coefficient of VSATCV, unit "m^VSATCVLEXP"
VSATCVLEXP = 0.0        # Length dependence coefficient of VSATCV, unit "m^VSATCVLEXP"
VSATCVW = 0.0            # Width dependence coefficient of VSATCV, unit "m^VSATCVWEXP"
VSATCVWEXP = 0.0        # Width dependence coefficient of VSATCV, unit "m^VSATCVWEXP"
VSATCVWL = 0.0           # Width-length dependence coefficient of VSATCV, unit "m^(2*VSATCVWLEXP)"
VSATCVWLEXP = 0.0       # Width-length dependence coefficient of VSATCV, unit "m^(2*VSATCVWLEXP)"

# Mobility degradation
UP1 = 0.0                # Mobility channel length coefficient, range (-inf, inf), unit ""
LP1 = 1.0e-8             # Mobility channel length exponential coefficient, except 0.0, unit "m"
UP2 = 0.0                # Mobility channel length coefficient, range (-inf, inf), unit ""
LP2 = 1.0e-8             # Mobility channel length exponential coefficient, except 0.0, unit "m"
U0 = 1.0e-8             # Mobility channel length exponential coefficient, unit "m"
U0L = 0.0                # Length dependence coefficient of U0L, unit "m^U0LEXP"
U0LEXP = 0.0            # Length dependence coefficient of U0L, unit "m^U0LEXP"
LU0 = 0.0                # Length dependence of U0, unit "m^3/V/s"
WU0 = 0.0                # Width dependence of U0, unit "m^3/V/s"
PU0 = 0.0                # Area dependence of U0, unit "m^4/V/s"
U0R = U0                 # Reverse-mode Low Field mobility., unit "m^2/V/s"
LU0R = LU0               # Length dependence of U0R, unit "m^3/V/s"
WU0R = WU0               # Width dependence of U0R, unit "m^3/V/s"
PU0R = PU0               # Area dependence of U0R, unit "m^4/V/s"
ETAMOB = 1.0             # Effective field parameter (should be kept close to 1), unit ""
UA = 0.001               # Mobility reduction coefficient, unit "(m/V)^EU"
UAL = 0.0                # Length dependence coefficient of  UA, unit "m^UALEXP"
UALEXP = 0.0            # Length dependence coefficient of  UA, unit "m^UALEXP"
UAW = 0.0                # Width dependence coefficient of UA, unit "m^UAWEXP"
UAWEXP = 0.0            # Width dependence coefficient of UA, unit "m^UAWEXP"
UAWL = 0.0               # Width-length dependence coefficient of UA, unit "m^UAWLEXP"
UAWLEXP = 0.0           # Width-length dependence coefficient of UA, unit "m^UAWLEXP"
LUA = 0.0                # Length dependence of UA, unit "m*(m/V)^EU"
WUA = 0.0                # Width dependence of UA, unit "m*(m/V)^EU"
PUA = 0.0                # Area dependence of UA, unit "m^2*(m/V)^EU"
UAR = UA                 # Reverse-mode mobility reduction coefficient, unit "(m/V)^EU"
LUAR = LUA               # Length dependence of UAR, unit "m*(m/V)^EU"
WUAR = WUA               # Width dependence of UAR, unit "m*(m/V)^EU"
PUAR = PUA               # Area dependence of UAR, unit "m^2*(m/V)^EU"
EU = 1.5                 # Mobility reduction exponent, unit ""
LEU = 0.0                # Length dependence of EU, unit "m"
WEU = 0.0                # Width dependence of EU, unit "m"
PEU = 0.0                # Area dependence of EU, unit "m^2"
EUL = 0.0                # Length dependence coefficient of EU, unit "m^EULEXP"
EULEXP = 0.0            # Length dependence coefficient of EU, unit "m^EULEXP"
EUW = 0.0                # Width dependence coefficient of EU, unit "m^EUWEXP"
EUWEXP = 0.0            # Width dependence coefficient of EU, unit "m^EUWEXP"
EUWL = 0.0               # Width-length dependence coefficient of EU, unit "m^EUWLEXP"
EUWLEXP = 0.0           # Width-length dependence coefficient of EU, unit "m^EUWLEXP"
UD = 0.001               # Coulomb scattering parameter, unit ""
UDL = 0.0                # Length dependence coefficient of UD, unit "m^UDLEXP"
UDLEXP = 0.0            # Length dependence coefficient of UD, unit "m^UDLEXP"
LUD = 0.0                # Length dependence of UD, unit "m"
WUD = 0.0                # Width dependence of UD, unit "m"
PUD = 0.0                # Area dependence of UD, unit "m^2"
UDR = UD                 # Reverse-mode Coulomb scattering parameter, unit ""
LUDR = LUD               # Length dependence of UDR, unit "m"
WUDR = WUD               # Width dependence of UDR, unit "m"
PUDR = PUD               # Area dependence of UDR, unit "m^2"
UCS = 2.0                # Coulomb scattering parameter, unit ""
LUCS = 0.0               # Length dependence of UCS, unit "m"
WUCS = 0.0               # Width dependence of UCS, unit "m"
PUCS = 0.0               # Area dependence of UCS, unit "m^2"
UCSR = UCS               # Reverse-mode Coulomb scattering parameter, unit ""
LUCSR = LUCS             # Length dependence of UCSR, unit "m"
WUCSR = WUCS             # Width dependence of UCSR, unit "m"
PUCSR = PUCS             # Area dependence of UCSR, unit "m^2"
UC = 0.0                 # Mobility reduction with body bias, unit "(m/V)^EU/V"
UCL = 0.0                # Length dependence coefficient of UC, unit "m^UCLEXP"
UCLEXP = 0.0            # Length dependence coefficient of UC, unit "m^UCLEXP"
UCW = 0.0                # Width dependence coefficient of UC, unit "m^UCWEXP"
UCWEXP = 0.0            # Width dependence coefficient of UC, unit "m^UCWEXP"
UCWL = 0.0               # Width-length dependence coefficient of UC, unit "m^(2*UCWLEXP)"
UCWLEXP = 0.0           # Width-length dependence coefficient of UC, unit "m^(2*UCWLEXP)"
LUC = 0.0                # Length dependence of UC, unit "m*(m/V)^EU/V"
WUC = 0.0                # Width dependence of UC, unit "m*(m/V)^EU/V"
PUC = 0.0                # Area dependence of UC, unit "m^2*(m/V)^EU/V"
UCR = UC                 # Reverse-mode mobility reduction with body bias, unit "(m/V)^EU/V"
LUCR = LUC               # Length dependence of UCR, unit "m*(m/V)^EU/V"
WUCR = WUC               # Width dependence of UCR, unit "m*(m/V)^EU/V"
PUCR = PUC               # Area dependence of UCR, unit "m^2*(m/V)^EU/V"

# Channel length modulation
PCLM = 0.0               # CLM pre-factor, unit ""
PCLML = 0.0              # Length dependence coefficient of PCLM, unit "m^PCLMLEXP"
PCLMLEXP = 0.0          # Length dependence coefficient of PCLM, unit "m^PCLMLEXP"
LPCLM = 0.0              # Length dependence of PCLM, unit "m"
WPCLM = 0.0              # Width dependence of PCLM, unit "m"
PPCLM = 0.0              # Area dependence of PCLM, unit "m^2"
PCLMR = PCLM             # Reverse-mode CLM pre-factor, unit ""
LPCLMR = LPCLM           # Length dependence of PCLMR, unit "m"
WPCLMR = WPCLM           # Width dependence of PCLMR, unit "m"
PPCLMR = PPCLM           # Area dependence of PCLMR, unit "m^2"
PCLMG = 0.0              # CLM pre-factor gate voltage dependence, unit "V"
PCLMCV = PCLM            # CLM parameter for C-V, unit ""
PCLMCVL = PCLML          # Length dependence coefficient of PCLMCV, unit "m^PCLMLEXP"
PCLMCVLEXP = PCLML      # Length dependence coefficient of PCLMCV, unit "m^PCLMLEXP"
LPCLMCV = LPCLM          # Length dependence of PCLMCV, unit "m"
WPCLMCV = WPCLM          # Width dependence of PCLMCV, unit "m"
PPCLMCV = PPCLM          # Area dependence of PCLMCV, unit "m^2"
PSCBE1 = 4.24e8          # Substrate current body-effect coefficient, unit "V/m"
LPSCBE1 = 0.0            # Length dependence of PSCBE1, unit "V"
WPSCBE1 = 0.0            # Width dependence of PSCBE1, unit "V"
PPSCBE1 = 0.0            # Area dependence of PSCBE1, unit "V*m"
PSCBE2 = 1.0e-8          # Substrate current body-effect coefficient, unit "m/V"
LPSCBE2 = 0.0            # Length dependence of PSCBE2, unit "m^2/V"
WPSCBE2 = 0.0            # Width dependence of PSCBE2, unit "m^2/V"
PPSCBE2 = 0.0            # Area dependence of PSCBE2, unit "m^3/V"
PDITS = 0.0              # Coefficient for drain-induced Vth shift, unit "1/V"
LPDITS = 0.0             # Length dependence of PDITS, unit "m/V"
WPDITS = 0.0             # Width dependence of PDITS, unit "m/V"
PPDITS = 0.0             # Area dependence of PDITS, unit "m^2/V"
PDITSL = 0.0             # L dependence of drain-induced Vth shift, unit "1/m"
PDITSD = 0.0             # Vds dependence of drain-induced Vth shift, unit "1/V"
LPDITSD = 0.0            # Length dependence of PDITSD, unit "m/V"
WPDITSD = 0.0            # Width dependence of PDITSD, unit "m/V"
PPDITSD = 0.0            # Area dependence of PDITSD, unit "m^2/V"

# S/D series resistances
RSH = 0.0                # Source-drain sheet resistances, unit "ohm/square"
PRWG = 1.0               # Gate bias dependence of S/D extension resistances, unit "1/V"
LPRWG = 0.0              # Length dependence of PRWG, unit "m/V"
WPRWG = 0.0              # Width dependence of PRWG, unit "m/V"
PPRWG = 0.0              # Area dependence of PRWG, unit "m^2/V"
PRWB = 0.0               # Body bias dependence of resistances, unit "1/V"
LPRWB = 0.0              # Length dependence of PRWB, unit "m/V"
WPRWB = 0.0              # Width dependence of PRWB, unit "m/V"
PPRWB = 0.0              # Area dependence of PRWB, unit "m^2/V"
PRWBL = 0.0              # Length dependence coefficient of PPRWB, unit "m^PRWBLEXP"
PRWBLEXP = 0.0          # Length dependence coefficient of PPRWB, unit "m^PRWBLEXP"
WR = 1.0                 # W dependence parameter of S/D extension resistances, unit ""
LWR = 0.0                # Length dependence of WR, unit "m"
WWR = 0.0                # Width dependence of WR, unit "m"
PWR = 0.0                # Area dependence of WR, unit "m^2"
RSWMIN = 0.0             # Source resistance per unit width at high Vgs (RDSMOD=1), unit "ohm*m^WR"
LRSWMIN = 0.0            # Length dependence of RSWMIN, unit "ohm*m^(2*WR)"
WRSWMIN = 0.0            # Width dependence of RSWMIN, unit "ohm*m^(2*WR)"
PRSWMIN = 0.0            # Area dependence of RSWMIN, unit "ohm*m^(3*WR)"
RSW = 10.0               # Zero bias source resistance (RDSMOD=1), unit "ohm*m^WR"
LRSW = 0.0               # Length dependence of RSW, unit "ohm*m^(2*WR)"
WRSW = 0.0               # Width dependence of RSW, unit "ohm*m^(2*WR)"
PRSW = 0.0               # Area dependence of RSW, unit "ohm*m^(3*WR)"
RSWL = 0.0               # Geometrical scaling of RSW (RDSMOD=1), unit "m^RSWLEXP"
RSWLEXP = 0.0           # Geometrical scaling of RSW (RDSMOD=1), unit "m^RSWLEXP"
RDWMIN = RSWMIN          # Drain resistance per unit width at high Vgs (RDSMOD=1), unit "ohm*m^WR"
LRDWMIN = LRSWMIN        # Length dependence of RDWMIN, unit "ohm*m^(2*WR)"
WRDWMIN = WRSWMIN        # Width dependence of RDWMIN, unit "ohm*m^(2*WR)"
PRDWMIN = PRSWMIN        # Area dependence of RDWMIN, unit "ohm*m^(3*WR)"
RDW = RSW                # Zero bias drain resistance (RDSMOD=1), unit "ohm*m^WR"
LRDW = LRSW              # Length dependence of RDW, unit "ohm*m^(2*WR)"
WRDW = WRSW              # Width dependence of RDW, unit "ohm*m^(2*WR)"
PRDW = PRSW              # Area dependence of RDW, unit "ohm*m^(3*WR)"
RDWL = RSWL              # Geometrical scaling of RDW (RDSMOD=1), unit "m^RDWLEXP"
RDWLEXP = RSWL          # Geometrical scaling of RDW (RDSMOD=1), unit "m^RDWLEXP"
RDSWMIN = 0.0            # S/D Resistance per unit width at high Vgs (RDSMOD=0 and RDSMOD=2), unit "ohm*m^WR"
LRDSWMIN = 0.0           # Length dependence of RDSWMIN, unit "ohm*m^(2*WR)"
WRDSWMIN = 0.0           # Width dependence of RDSWMIN, unit "ohm*m^(2*WR)"
PRDSWMIN = 0.0           # Area dependence of RDSWMIN, unit "ohm*m^(3*WR)"
RDSW = 20.0              # Zero bias resistance (RDSMOD=0 and RDSMOD=2), unit "ohm*um^WR"
RDSWL = 0.0              # Geometrical scaling of RDSW (RDSMOD=0 and RDSMOD=2), unit "m^RDSWLEXP"
RDSWLEXP = 0.0          # Geometrical scaling of RDSW (RDSMOD=0 and RDSMOD=2), unit "m^RDSWLEXP"
LRDSW = 0.0              # Length dependence of RDSW, unit "ohm*m^(2*WR)"
WRDSW = 0.0              # Width dependence of RDSW, unit "ohm*m^(2*WR)"
PRDSW = 0.0              # Area dependence of RDSW, unit "ohm*m^(3*WR)"

# Velocity saturation
PSAT = 1.0               # Gmsat variation with gate bias, unit ""
LPSAT = 0.0              # Length dependence of PSAT, unit "m"
WPSAT = 0.0              # Width dependence of PSAT, unit "m"
PPSAT = 0.0              # Area dependence of PSAT, unit "m^2"
PSATL = 0.0              # Length dependence coefficient of PSATL, unit "m^PSATLEXP"
PSATLEXP = 0.0          # Length dependence coefficient of PSATL, unit "m^PSATLEXP"
PSATB = 0.0              # Body bias effect on Idsat, unit "1/V"
PSATR = PSAT             # Reverse-mode Gmsat variation with gate bias, unit ""
LPSATR = LPSAT           # Length dependence of PSATR, unit "m"
WPSATR = WPSAT           # Width dependence of PSATR, unit "m"
PPSATR = PPSAT           # Area dependence of PSATR, unit "m^2"
LPSATB = 0.0             # Length dependence of PSATB, unit "m/V"
WPSATB = 0.0             # Width dependence of PSATB, unit "m/V"
PPSATB = 0.0             # Area dependence of PSATB, unit "m^2/V"
PSATX = 0.0             # Area dependence of PSATB, unit "m^2/V"
PTWG = 0.0               # Idsat variation with gate bias, unit ""
LPTWG = 0.0              # Length dependence of PTWG, unit "m"
WPTWG = 0.0              # Width dependence of PTWG, unit "m"
PPTWG = 0.0              # Area dependence of PTWG, unit "m^2"
PTWGL = 0.0              # Length dependence coefficient of PTWG, unit "m^PTWGLEXP"
PTWGLEXP = 0.0          # Length dependence coefficient of PTWG, unit "m^PTWGLEXP"
PTWGR = PTWG             # Reverse-mode Idsat variation with gate bias, unit ""
LPTWGR = LPTWG           # Length dependence of PTWGR, unit "m"
WPTWGR = WPTWG           # Width dependence of PTWGR, unit "m"
PPTWGR = PPTWG           # Area dependence of PTWGR, unit "m^2"
PTWGLR = PTWGL           # Length dependence coefficient of PTWG, unit "m^PTWGLEXPR"
PTWGLEXPR = PTWGL       # Length dependence coefficient of PTWG, unit "m^PTWGLEXPR"

# Velocity non-saturation effect
A1 = 0.0                 # Non-saturation effect parameter for strong inversion region, unit "1/V^2"
LA1 = 0.0                # Length dependence of A1, unit "m/V^2"
WA1 = 0.0                # Width dependence of A1, unit "m/V^2"
PA1 = 0.0                # Area dependence of A1, unit "m^2/V^2"
A11 = 0.0                # Temperature dependence of A1, unit ""
LA11 = 0.0               # Length dependence of A11, unit "m"
WA11 = 0.0               # Width dependence of A11, unit "m"
PA11 = 0.0               # Area dependence of A11, unit "m^2"
A2 = 0.0                 # Non-saturation effect parameter for moderate inversion region, unit "1/V"
LA2 = 0.0                # Length dependence of A2, unit "m/V"
WA2 = 0.0                # Width dependence of A2, unit "m/V"
PA2 = 0.0                # Area dependence of A2, unit "m^2/V"
A21 = 0.0                # Temperature dependence of A2, unit ""
LA21 = 0.0               # Length dependence of A21, unit "m"
WA21 = 0.0               # Width dependence of A21, unit "m"
PA21 = 0.0               # Area dependence of A21, unit "m^2"

# Output conductance
PDIBLC = 0.0             # Parameter for DIBL effect on Rout, unit ""
PDIBLCL = 0.0            # Length dependence coefficient of PDIBLC, unit "m^PDIBLCLEXP"
PDIBLCLEXP = 0.0        # Length dependence coefficient of PDIBLC, unit "m^PDIBLCLEXP"
LPDIBLC = 0.0            # Length dependence of PDIBLC, unit "m"
WPDIBLC = 0.0            # Width dependence of PDIBLC, unit "m"
PPDIBLC = 0.0            # Area dependence of PDIBLC, unit "m^2"
PDIBLCR = PDIBLC         # Reverse-mode parameter for DIBL effect on Rout, unit ""
PDIBLCLR = PDIBLCL       # Length dependence coefficient of PDIBLC, unit "m^PDIBLCLEXPR"
PDIBLCLEXPR = PDIBLCL   # Length dependence coefficient of PDIBLC, unit "m^PDIBLCLEXPR"
LPDIBLCR = LPDIBLC       # Length dependence of PDIBLCR, unit "m"
WPDIBLCR = WPDIBLC       # Width dependence of PDIBLCR, unit "m"
PPDIBLCR = PPDIBLC       # Area dependence of PDIBLCR, unit "m^2"
PDIBLCB = 0.0            # Parameter for DIBL effect on Rout, unit "1/V"
LPDIBLCB = 0.0           # Length dependence of PDIBLCB, unit "m/V"
WPDIBLCB = 0.0           # Width dependence of PDIBLCB, unit "m/V"
PPDIBLCB = 0.0           # Area dependence of PDIBLCB, unit "m^2/V"
PVAG = 1.0               # Vg dependence of early voltage, unit ""
LPVAG = 0.0              # Length dependence of PVAG, unit "m"
WPVAG = 0.0              # Width dependence of PVAG, unit "m"
PPVAG = 0.0              # Area dependence of PVAG, unit "m^2"
FPROUT = 0.0             # Gds degradation factor due to pocket implants, unit "V/m^0.5"
FPROUTL = 0.0            # Length dependence coefficient of FPROUT, unit "m^FPROUTLEXP"
FPROUTLEXP = 0.0        # Length dependence coefficient of FPROUT, unit "m^FPROUTLEXP"
LFPROUT = 0.0            # Length dependence of FPROUT, unit "V*m^0.5"
WFPROUT = 0.0            # Width dependence of FPROUT, unit "V*m^0.5"
PFPROUT = 0.0            # Area dependence of FPROUT, unit "V*m^1.5"

# Impact ionization current
ALPHA0 = 0.0             # First parameter of Iii, unit "m/V"
ALPHA0L = 0.0            # Length dependence coefficient of ALPHA0, unit "m^ALPHA0LEXP"
ALPHA0LEXP = 0.0        # Length dependence coefficient of ALPHA0, unit "m^ALPHA0LEXP"
LALPHA0 = 0.0            # Length dependence of ALPHA0, unit "m^2/V"
WALPHA0 = 0.0            # Width dependence of ALPHA0, unit "m^2/V"
PALPHA0 = 0.0            # Area dependence of ALPHA0, unit "m^3/V"
BETA0 = 0.0              # Vds dependent parameter of Iii, unit "1/V"
LBETA0 = 0.0             # Length dependence of BETA0, unit "m/V"
WBETA0 = 0.0             # Width dependence of BETA0, unit "m/V"
PBETA0 = 0.0             # Area dependence of BETA0, unit "m^2/V"

# Gate dielectric tunnelling current model parameters
AIGBACC = 1.36e-2        # Parameter for Igb, unit "(F*s^2/g)^0.5/m"
BIGBACC = 1.71e-3        # Parameter for Igb, unit "(F*s^2/g)^0.5/m/V"
CIGBACC = 0.075          # Parameter for Igb, unit "1/V"
NIGBACC = 1.0            # Parameter for Igbacc slope, unit ""
AIGBINV = 1.11e-2        # Parameter for Igb, unit "(F*s^2/g)^0.5/m"
BIGBINV = 9.49e-4        # Parameter for Igb, unit "(F*s^2/g)^0.5/m/V"
CIGBINV = 0.006          # Parameter for Igb, unit "1/V"
EIGBINV = 1.1            # Parameter for the Si bandgap for Igbinv, unit "V"
NIGBINV = 3.0            # Parameter for Igbinv slope, unit ""
AIGC = ((TYPE == `ntype) ? 1.36e-2 : 9.8e-3)# Parameter for Igc, unit "(F*s^2/g)^0.5/m"
BIGC = ((TYPE == `ntype) ? 1.71e-3 : 7.59e-4)# Parameter for Igc, unit "(F*s^2/g)^0.5/m/V"
CIGC = ((TYPE == `ntype) ? 0.075 : 0.03)# Parameter for Igc, unit "1/V"
AIGS = ((TYPE == `ntype) ? 1.36e-2 : 9.8e-3)# Parameter for Igs, unit "(F*s^2/g)^0.5/m"
BIGS = ((TYPE == `ntype) ? 1.71e-3 : 7.59e-4)# Parameter for Igs, unit "(F*s^2/g)^0.5/m/V"
CIGS = ((TYPE == `ntype) ? 0.075 : 0.03)# Parameter for Igs, unit "1/V"
AIGD = ((TYPE == `ntype) ? 1.36e-2 : 9.8e-3)# Parameter for Igd, unit "(F*s^2/g)^0.5/m"
BIGD = ((TYPE == `ntype) ? 1.71e-3 : 7.59e-4)# Parameter for Igd, unit "(F*s^2/g)^0.5/m/V"
CIGD = ((TYPE == `ntype) ? 0.075 : 0.03)# Parameter for Igd, unit "1/V"
DLCIG = LINT             # Delta L for Ig model, unit "m"
DLCIGD = DLCIG           # Delta L for Ig model, unit "m"
POXEDGE = 1.0            # Factor for the gate edge Tox, unit ""
NTOX = 1.0               # Exponent for Tox ratio, unit ""
TOXREF = 1.0            # Exponent for Tox ratio, unit ""
PIGCD = 1.0              # Igc, S/D partition parameter, range (-50.0, 50.0), unit ""
AIGCL = 0.0              # Length dependence coefficient of AIGC, unit "m"
AIGCW = 0.0              # Width dependence coefficient of AIGC, unit "m"
AIGSL = 0.0              # Length dependence coefficient of AIGS, unit "m"
AIGSW = 0.0              # Width dependence coefficient of AIGS, unit "m"
AIGDL = 0.0              # Length dependence coefficient of AIGD, unit "m"
AIGDW = 0.0              # Width dependence coefficient of AIGD, unit "m"
PIGCDL = 0.0             # Length dependence coefficient of PIGCD, unit "m"
LAIGBINV = 0.0           # Length dependence of AIGBINV, unit "(F*s^2/g)^0.5"
WAIGBINV = 0.0           # Width dependence of AIGBINV, unit "(F*s^2/g)^0.5"
PAIGBINV = 0.0           # Area dependence of AIGBINV, unit "m*(F*s^2/g)^0.5"
LBIGBINV = 0.0           # Length dependence of BIGBINV, unit "(F*s^2/g)^0.5/V"
WBIGBINV = 0.0           # Width dependence of BIGBINV, unit "(F*s^2/g)^0.5/V"
PBIGBINV = 0.0           # Area dependence of BIGBINV, unit "m*(F*s^2/g)^0.5/V"
LCIGBINV = 0.0           # Length dependence of CIGBINV, unit "m/V"
WCIGBINV = 0.0           # Width dependence of CIGBINV, unit "m/V"
PCIGBINV = 0.0           # Area dependence of CIGBINV, unit "m^2/V"
LEIGBINV = 0.0           # Length dependence of EIGBINV, unit "m*V"
WEIGBINV = 0.0           # Width dependence of EIGBINV, unit "m*V"
PEIGBINV = 0.0           # Area dependence of EIGBINV, unit "m^2*V"
LNIGBINV = 0.0           # Length dependence of NIGBINV, unit "m"
WNIGBINV = 0.0           # Width dependence of NIGBINV, unit "m"
PNIGBINV = 0.0           # Area dependence of NIGBINV, unit "m^2"
LAIGBACC = 0.0           # Length dependence of AIGBACC, unit "(F*s^2/g)^0.5"
WAIGBACC = 0.0           # Width dependence of AIGBACC, unit "(F*s^2/g)^0.5"
PAIGBACC = 0.0           # Area dependence of AIGBACC, unit "m*(F*s^2/g)^0.5"
LBIGBACC = 0.0           # Length dependence of BIGBACC, unit "(F*s^2/g)^0.5/V"
WBIGBACC = 0.0           # Width dependence of BIGBACC, unit "(F*s^2/g)^0.5/V"
PBIGBACC = 0.0           # Area dependence of BIGBACC, unit "m*(F*s^2/g)^0.5/V"
LCIGBACC = 0.0           # Length dependence of CIGBACC, unit "m/V"
WCIGBACC = 0.0           # Width dependence of CIGBACC, unit "m/V"
PCIGBACC = 0.0           # Area dependence of CIGBACC, unit "m^2/V"
LNIGBACC = 0.0           # Length dependence of NIGBACC, unit "m"
WNIGBACC = 0.0           # Width dependence of NIGBACC, unit "m"
PNIGBACC = 0.0           # Area dependence of NIGBACC, unit "m^2"
LAIGC = 0.0              # Length dependence of AIGC, unit "(F*s^2/g)^0.5"
WAIGC = 0.0              # Width dependence of AIGC, unit "(F*s^2/g)^0.5"
PAIGC = 0.0              # Area dependence of AIGC, unit "m*(F*s^2/g)^0.5"
LBIGC = 0.0              # Length dependence of BIGC, unit "(F*s^2/g)^0.5/V"
WBIGC = 0.0              # Width dependence of BIGC, unit "(F*s^2/g)^0.5/V"
PBIGC = 0.0              # Area dependence of BIGC, unit "m*(F*s^2/g)^0.5/V"
LCIGC = 0.0              # Length dependence of CIGC, unit "m/V"
WCIGC = 0.0              # Width dependence of CIGC, unit "m/V"
PCIGC = 0.0              # Area dependence of CIGC, unit "m^2/V"
LAIGS = 0.0              # Length dependence of AIGS, unit "(F*s^2/g)^0.5"
WAIGS = 0.0              # Width dependence of AIGS, unit "(F*s^2/g)^0.5"
PAIGS = 0.0              # Area dependence of AIGS, unit "m*(F*s^2/g)^0.5"
LBIGS = 0.0              # Length dependence of BIGS, unit "(F*s^2/g)^0.5/V"
WBIGS = 0.0              # Width dependence of BIGS, unit "(F*s^2/g)^0.5/V"
PBIGS = 0.0              # Area dependence of BIGS, unit "m*(F*s^2/g)^0.5/V"
LCIGS = 0.0              # Length dependence of CIGS, unit "m/V"
WCIGS = 0.0              # Width dependence of CIGS, unit "m/V"
PCIGS = 0.0              # Area dependence of CIGS, unit "m^2/V"
LAIGD = 0.0              # Length dependence of AIGD, unit "(F*s^2/g)^0.5"
WAIGD = 0.0              # Width dependence of AIGD, unit "(F*s^2/g)^0.5"
PAIGD = 0.0              # Area dependence of AIGD, unit "m*(F*s^2/g)^0.5"
LBIGD = 0.0              # Length dependence of BIGD, unit "(F*s^2/g)^0.5/V"
WBIGD = 0.0              # Width dependence of BIGD, unit "(F*s^2/g)^0.5/V"
PBIGD = 0.0              # Area dependence of BIGD, unit "m*(F*s^2/g)^0.5/V"
LCIGD = 0.0              # Length dependence of CIGD, unit "m/V"
WCIGD = 0.0              # Width dependence of CIGD, unit "m/V"
PCIGD = 0.0              # Area dependence of CIGD, unit "m^2/V"
LPOXEDGE = 0.0           # Length dependence of POXEDGE, unit "m"
WPOXEDGE = 0.0           # Width dependence of POXEDGE, unit "m"
PPOXEDGE = 0.0           # Area dependence of POXEDGE, unit "m^2"
LDLCIG = 0.0             # Length dependence of DLCIG, unit "m^2"
WDLCIG = 0.0             # Width dependence of DLCIG, unit "m^2"
PDLCIG = 0.0             # Area dependence of DLCIG, unit "m^3"
LDLCIGD = 0.0            # Length dependence of DLCIGD, unit "m^2"
WDLCIGD = 0.0            # Width dependence of DLCIGD, unit "m^2"
PDLCIGD = 0.0            # Area dependence of DLCIGD, unit "m^3"
LNTOX = 0.0              # Length dependence of NTOX, unit "m"
WNTOX = 0.0              # Width dependence of NTOX, unit "m"
PNTOX = 0.0              # Area dependence of NTOX, unit "m^2"

# GIDL and GISL currents
AGIDL = 0.0              # Pre-exponential coefficient for GIDL, unit "V/m"
AGIDLL = 0.0             # Length dependence coefficient of AGIDL, unit "m"
AGIDLW = 0.0             # Width dependence coefficient of AGIDL, unit "m"
LAGIDL = 0.0             # Length dependence of AGIDL, unit "m^2"
WAGIDL = 0.0             # Width dependence of AGIDL, unit "m^2"
PAGIDL = 0.0             # Area dependence of AGIDL, unit "m^3"
BGIDL = 2.3e9            # Exponential coefficient for GIDL, unit "V/m"
LBGIDL = 0.0             # Length dependence of BGIDL, unit "V"
WBGIDL = 0.0             # Width dependence of BGIDL, unit "V"
PBGIDL = 0.0             # Area dependence of BGIDL, unit "V*m"
CGIDL = 0.5              # Exponential coefficient for GIDL, unit "V/m"
LCGIDL = 0.0             # Length dependence of CGIDL, unit "V"
WCGIDL = 0.0             # Width dependence of CGIDL, unit "V"
PCGIDL = 0.0             # Area dependence of CGIDL, unit "V*m"
EGIDL = 0.8              # Band bending parameter for GIDL, unit "V"
LEGIDL = 0.0             # Length dependence of EGIDL, unit "V*m"
WEGIDL = 0.0             # Width dependence of EGIDL, unit "V*m"
PEGIDL = 0.0             # Area dependence of EGIDL, unit "V*m^2"
AGISL = AGIDL            # Pre-exponential coefficient for GISL, unit "V/m"
AGISLL = AGIDLL          # Length dependence coefficient of AGISL, unit "m"
AGISLW = AGIDLW          # Width dependence coefficient of AGISL, unit "m"
LAGISL = LAGIDL          # Length dependence of AGISL, unit "m^2"
WAGISL = WAGIDL          # Width dependence of AGISL, unit "m^2"
PAGISL = PAGIDL          # Area dependence of AGISL, unit "m^3"
BGISL = BGIDL            # Exponential coefficient for GISL, unit "V/m"
LBGISL = LBGIDL          # Length dependence of BGISL, unit "V"
WBGISL = WBGIDL          # Width dependence of BGISL, unit "V"
PBGISL = PBGIDL          # Area dependence of BGISL, unit "V*m"
CGISL = CGIDL            # Exponential coefficient for GISL, unit "V/m"
LCGISL = LCGIDL          # Length dependence of CGISL, unit "V"
WCGISL = WCGIDL          # Width dependence of CGISL, unit "V"
PCGISL = PCGIDL          # Area dependence of CGISL, unit "V*m"
EGISL = EGIDL            # Band bending parameter for GISL, unit "V"
LEGISL = LEGIDL          # Length dependence of EGISL, unit "V*m"
WEGISL = WEGIDL          # Width dependence of EGISL, unit "V*m"
PEGISL = PEGIDL          # Area dependence of EGISL, unit "V*m^2"

# Overlap capacitance and fringing capacitance
CF = 0.0                 # Outer fringe capacitance, unit "F/m"
LCF = 0.0                # Length dependence of CF, unit "F"
WCF = 0.0                # Width dependence of CF, unit "F"
PCF = 0.0                # Area dependence of CF, unit "F*m"
CFRCOEFF = 1.0           # Coefficient for outer fringe capacitance, range (1.0, inf), unit "F/m"
CGSO = 0.0               # Gate-to-source overlap capacitance, unit "F/m"
CGDO = 0.0               # Gate-to-drain overlap capacitance, unit "F/m"
CGBO = 0.0               # Gate-to-body overlap capacitance, unit "F/m"
CGSL = 0.0               # Overlap capacitance between gate and lightly-doped source region, unit "F/m"
LCGSL = 0.0              # Length dependence of CGSL, unit ""
WCGSL = 0.0              # Width dependence of CGSL, unit ""
PCGSL = 0.0              # Area dependence of CGSL, unit ""
CGDL = 0.0               # Overlap capacitance between gate and lightly-doped drain region, unit "F/m"
LCGDL = 0.0              # Length dependence of CGDL, unit "F"
WCGDL = 0.0              # Width dependence of CGDL, unit "F"
PCGDL = 0.0              # Area dependence of CGDL, unit "F*m"
CKAPPAS = 0.6            # Coefficient of bias-dependent overlap capacitance for the source side, unit "V"
LCKAPPAS = 0.0           # Length dependence of CKAPPAS, unit "m*V"
WCKAPPAS = 0.0           # Width dependence of CKAPPAS, unit "m*V"
PCKAPPAS = 0.0           # Area dependence of CKAPPAS, unit "m^2*V"
CKAPPAD = 0.6            # Coefficient of bias-dependent overlap capacitance for the drain side, unit "V"
LCKAPPAD = 0.0           # Length dependence of CKAPPAD, unit "m*V"
WCKAPPAD = 0.0           # Width dependence of CKAPPAD, unit "m*V"
PCKAPPAD = 0.0           # Area dependence of CKAPPAD, unit "m^2*V"

# Layout-dependent parasitics model parameters (resistance only)
DMCG = 0.0               # Distance of mid-contact to gate edge, unit "m"
DMCI = DMCG              # Distance of mid-contact to isolation, unit "m"
DMDG = 0.0               # Distance of mid-ciffusion to gate edge, unit "m"
DMCGT = 0.0              # Distance of id-contact to gate edge in test, unit "m"
XGL = 0.0                # Variation in Ldrawn, range (-inf, (L*LMLT+XL)), unit "m"
RSHG = 0.1               # Gate sheet resistance, unit "ohm"

# Junction capacitance
CJS = 5.0e-4             # Unit area source-side junction capacitance at zero bias, unit "F/m^2"
CJD = CJS                # Unit area drain-side junction capacitance at zero bias, unit "F/m^2"
CJSWS = 5.0e-10          # Unit length source-side side-wall junction capacitance at zero bias, unit "F/m"
CJSWD = CJSWS            # Unit length drain-side side-wall junction capacitance at zero bias, unit "F/m"
CJSWGS = 0.0             # Unit length source-side gate side-wall junction capacitance at zero bias, unit "F/m"
CJSWGD = CJSWGS          # Unit length drain-side gate side-wall junction capacitance at zero bias, unit "F/m"
PBS = 1.0                # Source-side bulk junction built-in potential, unit "V"
PBD = PBS                # Drain-side bulk junction built-in potential, unit "V"
PBSWS = 1.0              # Built-in potential for Source-side side-wall junction capacitance, unit "V"
PBSWD = PBSWS            # Built-in potential for Drain-side side-wall junction capacitance, unit "V"
PBSWGS = PBSWS           # Built-in potential for Source-side gate side-wall junction capacitance, unit "V"
PBSWGD = PBSWGS          # Built-in potential for Drain-side gate side-wall junction capacitance, unit "V"
MJS = 0.5                # Source bottom junction capacitance grading coefficient, unit ""
MJD = MJS                # Drain bottom junction capacitance grading coefficient, unit ""
MJSWS = 0.33             # Source side-wall junction capacitance grading coefficient, unit ""
MJSWD = MJSWS            # Drain side-wall junction capacitance grading coefficient, unit ""
MJSWGS = MJSWS           # Source-side gate side-wall junction capacitance grading coefficient, unit ""
MJSWGD = MJSWGS          # Drain-side gate side-wall junction capacitance grading coefficient, unit ""

# Junction current
JSS = 1.0e-4             # Bottom source junction reverse saturation current density, unit "A/m^2"
JSD = JSS                # Bottom drain junction reverse saturation current density, unit "A/m^2"
JSWS = 0.0               # Unit length reverse saturation current for side-wall source junction, unit "A/m"
JSWD = JSWS              # Unit length reverse saturation current for side-wall drain junction, unit "A/m"
JSWGS = 0.0              # Unit length reverse saturation current for gate-edge side-wall source junction, unit "A/m"
JSWGD = JSWGS            # Unit length reverse saturation current for gate-edge side-wall drain junction, unit "A/m"
NJS = JSWGS             # Unit length reverse saturation current for gate-edge side-wall drain junction, unit "A/m"
NJD = JSWGS             # Unit length reverse saturation current for gate-edge side-wall drain junction, unit "A/m"
IJTHSFWD = 0.1           # Forward source diode breakdown limiting current, unit "A"
IJTHDFWD = IJTHSFWD      # Forward drain diode breakdown limiting current, unit "A"
IJTHSREV = 0.1           # Reverse source diode breakdown limiting current, unit "A"
IJTHDREV = IJTHSREV      # Reverse drain diode breakdown limiting current, unit "A"
BVS = 10.0               # Source diode breakdown voltage, unit "V"
BVD = BVS                # Drain diode breakdown voltage, unit "V"
XJBVS = BVS             # Drain diode breakdown voltage, unit "V"
XJBVD = BVS             # Drain diode breakdown voltage, unit "V"

# Tunneling component of junction current
JTSS = 0.0               # Bottom source junction trap-assisted saturation current density, unit "A/m"
JTSD = JTSS              # Bottom drain junction trap-assisted saturation current density, unit "A/m"
JTSSWS = 0.0             # Unit length trap-assisted saturation current for side-wall source junction, unit "A/m^2"
JTSSWD = JTSSWS          # Unit length trap-assisted saturation current for side-wall drain junction, unit "A/m^2"
JTSSWGS = 0.0            # Unit length trap-assisted saturation current for gate-edge side-wall source junction, unit "A/m"
JTSSWGD = JTSSWGS        # Unit length trap-assisted saturation current for gate-edge side-wall drain junction, unit "A/m"
JTWEFF = 0.0             # Trap assisted tunnelling current width dependence, unit ""
NJTS = 20.0              # Non-ideality factor for JTSS, unit ""
NJTSD = NJTS             # Non-ideality factor for JTSD, unit ""
NJTSSW = 20.0            # Non-ideality factor for JTSSWS, unit ""
NJTSSWD = NJTSSW         # Non-ideality factor for JTSSWD, unit ""
NJTSSWG = 20.0           # Non-ideality factor for JTSSWGS, unit ""
NJTSSWGD = NJTSSWG       # Non-ideality factor for JTSSWGD, unit ""
VTSS = 10.0              # Bottom source junction trap-assisted current voltage dependent parameter, unit "V"
VTSD = VTSS              # Bottom drain junction trap-assisted current voltage dependent parameter, unit "V"
VTSSWS = 10.0            # Unit length trap-assisted current voltage dependent parameter for side-wall source junction, unit "V"
VTSSWD = VTSSWS          # Unit length trap-assisted current voltage dependent parameter for side-wall drain junction, unit "V"
VTSSWGS = 10.0           # Unit length trap-assisted current voltage dependent parameter for gate-edge side-wall source junction, unit "V"
VTSSWGD = VTSSWGS        # Unit length trap-assisted current voltage dependent parameter for gate-edge side-wall drain junction, unit "V"

# High-speed/RF model parameters
XRCRG1 = 12.0            # 1st fitting parameter the bias-dependent Rg , unit ""
XRCRG2 = 1.0             # 2nd fitting parameter the bias-dependent Rg , unit ""
GBMIN = 1.0e-12          # Minimum body conductance, unit "mho"
RBPS0 = 1.0e-12         # Minimum body conductance, unit "mho"
RBPSL = 0.0              # Length scaling parameter for RBPS, unit ""
RBPSW = 0.0              # Width scaling parameter for RBPS, unit ""
RBPSNF = 0.0             # Number of fingers scaling parameter for RBPS, unit ""
RBPD0 = 0.0             # Number of fingers scaling parameter for RBPS, unit ""
RBPDL = 0.0              # Length scaling parameter for RBPD, unit ""
RBPDW = 0.0              # Width scaling parameter for RBPD, unit ""
RBPDNF = 0.0             # Number of fingers scaling parameter for RBPD, unit ""
RBPBX0 = 0.0            # Number of fingers scaling parameter for RBPD, unit ""
RBPBXL = 0.0             # Length scaling parameter for RBPBX, unit ""
RBPBXW = 0.0             # Width scaling parameter for RBPBX, unit ""
RBPBXNF = 0.0            # Number of fingers scaling parameter for RBPBX, unit ""
RBPBY0 = 0.0            # Number of fingers scaling parameter for RBPBX, unit ""
RBPBYL = 0.0             # Length scaling parameter for RBPBY, unit ""
RBPBYW = 0.0             # Width scaling parameter for RBPBY, unit ""
RBPBYNF = 0.0            # Number of fingers scaling parameter for RBPBY, unit ""
RBSBX0 = 0.0            # Number of fingers scaling parameter for RBPBY, unit ""
RBSBY0 = 0.0            # Number of fingers scaling parameter for RBPBY, unit ""
RBDBX0 = 0.0            # Number of fingers scaling parameter for RBPBY, unit ""
RBDBY0 = 0.0            # Number of fingers scaling parameter for RBPBY, unit ""
RBSDBXL = 0.0            # Length scaling parameter for RBSBX and RBDBX, unit ""
RBSDBXW = 0.0            # Width scaling parameter for RBSBX and RBDBX, unit ""
RBSDBXNF = 0.0           # Number of fingers scaling parameter for RBSBX and RBDBX, unit ""
RBSDBYL = 0.0            # Length scaling parameter for RBSBY and RBDBY, unit ""
RBSDBYW = 0.0            # Width scaling parameter for RBSBY and RBDBY, unit ""
RBSDBYNF = 0.0           # Number of fingers scaling parameter for RBSBY and RBDBY, unit ""

# Flicker noise
`MPRoc( EF                ,1.0                                      ,""            ,0.0         ,2.0         ,"Flicker noise frequency exponent" )
EM = 4.1e7               # Saturation field, unit "V/m"
NOIA = 6.250e40          # Flicker noise parameter A, unit "s^(1-EF)/(eV)^1/m^3"
NOIB = 3.125e25          # Flicker noise parameter B, unit "s^(1-EF)/(eV)^1/m"
NOIC = 8.750e8           # Flicker noise parameter C, unit "s^(1-EF)*m/(eV)^1"
LINTNOI = 0.0            # Length reduction parameter offset, unit "m"
NOIA1 = 0.0              # Flicker noise fitting parameter in strong inversion, unit ""
NOIAX = 0.0             # Flicker noise fitting parameter in strong inversion, unit ""

# Thermal noise
NTNOI = 1.0              # Noise factor for short-channel devices for TNOIMOD=0 only, unit ""
RNOIA = 0.577            # Noise parameter for TNOIMOD = 1, unit ""
RNOIB = 0.5164           # Noise parameter for TNOIMOD = 1, unit ""
RNOIC = 0.395            # Noise parameter for TNOIMOD = 1, unit ""
TNOIA = 1.5              # Noise parameter for TNOIMOD = 1, range (-inf, inf), unit ""
TNOIB = 3.5              # Noise parameter for TNOIMOD = 1, range (-inf, inf), unit ""
TNOIC = 0.0              # Noise correlation coefficient for TNOIMOD = 1, range (-inf, inf), unit ""

# Binning parameters
BINUNIT = 1              # Unit of L and W for Binning, 1: micro-meter, 0: default, range (0, 1), unit 
DLBIN = 0.0              # Length reduction parameter for binning, unit ""
DWBIN = 0.0              # Width reduction parameter for binning, unit ""

# Temperature dependence parameters
TNOM = 27.0              # Temperature at which the model was extracted, unit "degC"
TBGASUB = 4.73e-4        # Bandgap temperature coefficient, unit "eV/K"
TBGBSUB = 636.0          # Bandgap temperature coefficient, unit "K"
TNFACTOR = 0.0           # Temperature exponent for NFACTOR, unit ""
UTE = -1.5               # Mobility temperature exponent, unit ""
LUTE = 0.0               # Length dependence of UTE, unit "m"
WUTE = 0.0               # Width dependence of UTE, unit "m"
PUTE = 0.0               # Area dependence of UTE, unit "m^2"
UTEL = 0.0               # Length scaling parameter for UTE, unit "m"
UA1 = 1.0e-3             # Temperature coefficient for UA, unit "m/V"
LUA1 = 0.0               # Length dependence of UA1, unit "m^2/V"
WUA1 = 0.0               # Width dependence of UA1, unit "m^2/V"
PUA1 = 0.0               # Area dependence of UA1, unit "m^3/V"
UA1L = 0.0               # Length scaling parameter for UA1, unit "m"
UC1 = 0.056e-9           # Temperature coefficient for UC, unit "1/K"
LUC1 = 0.0               # Length dependence of UC1, unit "m/K"
WUC1 = 0.0               # Width dependence of UC1, unit "m/K"
PUC1 = 0.0               # Area dependence of UC1, unit "m^2/K"
UD1 = 0.0                # Temperature coefficient for UD, unit "1/m^2"
LUD1 = 0.0               # Length dependence of UD1, unit "1/m"
WUD1 = 0.0               # Width dependence of UD1, unit "1/m"
PUD1 = 0.0               # Area dependence of UD1, unit ""
UD1L = 0.0               # Length scaling parameter for UD1, unit "m"
EU1 = 0.0                # Temperature coefficient for EU, unit ""
LEU1 = 0.0               # Length dependence of EU1, unit "m"
WEU1 = 0.0               # Width dependence of EU1, unit "m"
PEU1 = 0.0               # Area dependence of EU1, unit "m^2"
UCSTE = -4.775e-3        # Temperature coefficient for UCS, unit ""
LUCSTE = 0.0             # Length dependence of UCSTE, unit "m"
WUCSTE = 0.0             # Width dependence of UCSTE, unit "m"
PUCSTE = 0.0             # Area dependence of UCSTE, unit "m^2"
TETA0 = 0.0              # Temperature coefficient for ETA0, unit ""
PRT = 0.0                # Temperature coefficient for resistance, unit ""
LPRT = 0.0               # Length dependence of PRT, unit "m"
WPRT = 0.0               # Width dependence of PRT, unit "m"
PPRT = 0.0               # Area dependence of PRT, unit "m^2"
AT = -1.56e-3            # Temperature coefficient for saturation velocity, unit "m/s"
LAT = 0.0                # Length dependence of AT, unit "m^2/s"
WAT = 0.0                # Width dependence of AT, unit "m^2/s"
PAT = 0.0                # Area dependence of AT, unit "m^3/s"
ATL = 0.0                # Length Scaling parameter for AT, unit "m"
TDELTA = 0.0             # Temperature coefficient for DELTA, unit "1/K"
PTWGT = 0.0              # Temperature coefficient for PTWG, unit "1/K"
LPTWGT = 0.0             # Length dependence of PTWGT, unit "m/K"
WPTWGT = 0.0             # Width dependence of PTWGT, unit "m/K"
PPTWGT = 0.0             # Area dependence of PTWGT, unit "m^2/K"
PTWGTL = 0.0             # Length acaling parameter for PTWGT, unit "m"
KT1 = -0.11              # Temperature coefficient for Vth, unit "V"
KT1EXP = -0.11          # Temperature coefficient for Vth, unit "V"
KT1L = 0.0               # Temperature coefficient for Vth, unit "V*m"
LKT1 = 0.0               # Length dependence of KT1, unit "V*m"
WKT1 = 0.0               # Width dependence of KT1, unit "V*m"
PKT1 = 0.0               # Area dependence of KT1, unit "V*m^2"
KT2 = 0.022              # Temperature coefficient for Vth, unit ""
LKT2 = 0.0               # Length dependence of KT2, unit "m"
WKT2 = 0.0               # Width dependence of KT2, unit "m"
PKT2 = 0.0               # Area dependence of KT2, unit "m^2"
IIT = 0.0                # Temperature coefficient for BETA0, unit ""
LIIT = 0.0               # Length dependence of IIT, unit "m"
WIIT = 0.0               # Width dependence of IIT, unit "m"
PIIT = 0.0               # Area dependence of IIT, unit "m^2"
IGT = 2.5                # Gate current temperature dependence, unit ""
LIGT = 0.0               # Length dependence of IGT, unit "m"
WIGT = 0.0               # Width dependence of IGT, unit "m"
PIGT = 0.0               # Area dependence of IGT, unit "m^2"
TGIDL = 0.0              # Temperature coefficient for GIDL/GISL, unit "1/K"
LTGIDL = 0.0             # Length dependence of TGIDL, unit "m/K"
WTGIDL = 0.0             # Width dependence of TGIDL, unit "m/K"
PTGIDL = 0.0             # Area dependence of TGIDL, unit "m^2/K"
TCJ = 0.0                # Temperature coefficient for CJS/CJD, unit "1/K"
TCJSW = 0.0              # Temperature coefficient for CJSWS/CJSWD, unit "1/K"
TCJSWG = 0.0             # Temperature coefficient for CJSWGS/CJSWGD, unit "1/K"
TPB = 0.0                # Temperature coefficient for PBS/PBD, unit "V/K"
TPBSW = 0.0              # Temperature coefficient for PBSWS/PBSWD, unit "V/K"
TPBSWG = 0.0             # Temperature coefficient for PBSWGS/PBSWGD, unit "V/K"
XTIS = 3.0               # Source junction current temperature exponent, unit ""
XTID = XTIS              # Drain junction current temperature exponent, unit ""
XTSS = 0.02              # Power dependence of JTSS on temperature, unit ""
XTSD = XTSS              # Power dependence of JTSD on temperature, unit ""
XTSSWS = 0.02            # Power dependence of JTSSWS on temperature, unit ""
XTSSWD = XTSSWS          # Power dependence of JTSSWD on temperature, unit ""
XTSSWGS = 0.02           # Power dependence of JTSSWGS on temperature, unit ""
XTSSWGD = XTSSWGS        # Power dependence of JTSSWGD on temperature, unit ""
TNJTS = 0.0              # Temperature coefficient for NJTS, unit ""
TNJTSD = TNJTS           # Temperature coefficient for NJTSD, unit ""
TNJTSSW = 0.0            # Temperature coefficient for NJTSSW, unit ""
TNJTSSWD = TNJTSSW       # Temperature coefficient for NJTSSWD, unit ""
TNJTSSWG = 0.0           # Temperature coefficient for NJTSSWG, unit ""
TNJTSSWGD = TNJTSSWG     # Temperature coefficient for NJTSSWGD, unit ""

# Self heating parameters
RTH0 = 0.0               # Thermal resistance, range (0.0, inf), unit "m*K/W"
CTH0 = 1.0e-5            # Thermal capacitance, range (0.0, inf), unit "s*W/(m*K)"
WTH0 = 0.0               # Width dependence coefficient for Rth and Cth, unit "m"

# Stress related parameters
SAREF = 0.0             # Width dependence coefficient for Rth and Cth, unit "m"
SBREF = 0.0             # Width dependence coefficient for Rth and Cth, unit "m"
WLOD = 0.0               # Width parameter for stress effect, unit "m"
KU0 = 0.0                # Mobility degradation/enhancement parameter for stress effect, unit "m"
KVSAT = 0.0              # Saturation velocity degradation/enhancement parameter for stress effect, unit "m"
TKU0 = 0.0               # Temperature coefficient for KU0, unit ""
LKU0 = 0.0               # Length dependence of KU0, unit "m^LLODKU0"
WKU0 = 0.0               # Width dependence of KU0, unit "m^WLODKU0"
PKU0 = 0.0               # Cross-term dependence of KU0, unit "m^(LLODKU0+WLODKU0)"
LLODKU0 = 0.0            # Length parameter for U0 stress effect, unit ""
WLODKU0 = 0.0            # Width parameter for U0 stress effect, unit ""
KVTH0 = 0.0              # Threshold shift parameter for stress effect, unit "V*m"
LKVTH0 = 0.0             # Length dependence of KVTH0, unit "m^LLODKU0"
WKVTH0 = 0.0             # Width dependence of KVTH0, unit "m^WLODKU0"
PKVTH0 = 0.0             # Cross-term dependence of KVTH0, unit "m^(LLODKU0+WLODKU0)"
LLODVTH = 0.0            # Length parameter for Vth stress effect, unit ""
WLODVTH = 0.0            # Width parameter for Vth stress effect, unit ""
STK2 = 0.0               # K2 shift factor related to Vth change, unit "m"
LODK2 = 0.0              # K2 shift modification factor for stress effect, unit ""
STETA0 = 0.0             # ETA0 shift related to Vth0 change, unit "m"
LODETA0 = 0.0            # ETA0 modification factor for stress effect, unit ""

# Well proximity parameters
WEB = 0.0                # Coefficient for SCB (> 0), unit ""
WEC = 0.0                # Coefficient for SCC (> 0), unit ""
KVTH0WE = 0.0            # Threshold shift factor for well proximity effect, unit ""
LKVTH0WE = 0.0           # Length dependence of KVTH0WE, unit "m"
WKVTH0WE = 0.0           # Width dependence of KVTH0WE, unit "m"
PKVTH0WE = 0.0           # Area dependence of KVTH0WE, unit "m^2"
K2WE = 0.0               # K2 shift factor for well proximity effect, unit ""
LK2WE = 0.0              # Length dependence of K2WE, unit "m"
WK2WE = 0.0              # Width dependence of K2WE, unit "m"
PK2WE = 0.0              # Area dependence of K2WE, unit "m^2"
KU0WE = 0.0              # Mobility degradation factor for well proximity effect, unit ""
LKU0WE = 0.0             # Length dependence of KU0WE, unit "m"
WKU0WE = 0.0             # Width dependence of KU0WE, unit "m"
PKU0WE = 0.0             # Area dependence of KU0WE, unit "m^2"
SCREF = 1.0e-6           # Reference distance to calculate SCA,SCB and SCC (< 0), range (0.0, inf), unit "m"

# Sub-surface leakage drain current
SSL0 = 4.0e2             # Temperature- and doping-independent parameter for sub-surface leakage drain current, unit "A/m"
SSL1 = 3.36e8            # Temperature- and doping-independent parameter for gate length for sub-surface leakage drain current, unit "1/m"
SSL2 = 0.185             # Fitting parameter for sub-surface leakage drain current: barrier height, unit ""
SSL3 = 0.3               # Fitting parameter for sub-surface leakage drain current: gate voltage effect, unit "V"
SSL4 = 1.4               # Fitting parameter for sub-surface leakage drain current: gate voltage effect, unit "1/V"
SSL5 = 0                 # Fitting parameter for sub-surface leakage drain current: gate voltage effect, unit "1/V"
SSLEXP1 = 0.490          # Fitting exponent for SSL doping effect, unit ""
SSLEXP2 = 1.42           # Fitting exponent for SSL temperature, unit ""

# Vdsx smoothing
AVDSX = 20.0             # Smoothing parameter in Vdsx in Vbsx, range (5.0, 100.0), unit ""

# STI edge FET device parameters
WEDGE = 10.0e-9          # Edge FET width, range (1.0e-9, inf), unit "m"
DGAMMAEDGE = 0.0         # Different in body-bias coefficient between Edge-FET and Main-FET, range (-inf, inf), unit ""
DGAMMAEDGEL = 0.0        # L dependence parameter for DGAMMA, range (-inf, inf), unit ""
DGAMMAEDGELEXP = 1.0     # Exponent of L dependence parameter for DGAMMA, range (-inf, inf), unit ""
DVTEDGE = 0.0            # Vth shift for Edge FET, range (-inf, inf), unit ""
NDEPEDGE = 1e24          # Channel doping concentration for EDGEFET, unit "1/m^3"
LNDEPEDGE = 0.0          # Length dependence of NDEPEDGE, unit "1/m^2"
WNDEPEDGE = 0.0          # Width dependence of NDEPEDGE, unit "1/m^2"
PNDEPEDGE = 0.0          # Area dependence of NDEPEDGE, unit "1/m"
NFACTOREDGE = 0.0        # NFACTOR for Edge FET, unit ""
LNFACTOREDGE = 0.0       # Length dependence of NFACTOREDGE, unit "m"
WNFACTOREDGE = 0.0       # Width dependence of NFACTOREDGE, unit "m"
PNFACTOREDGE = 0.0       # Area dependence of NFACTOREDGE, unit "m^2"
CITEDGE = 0.0            # CIT for Edge FET, unit "F/m^2"
LCITEDGE = 0.0           # Length dependence of CITEDGE, unit "F/m"
WCITEDGE = 0.0           # Width dependence of CITEDGE, unit "F/m"
PCITEDGE = 0.0           # Area dependence of CITEDGE, unit "F"
CDSCDEDGE = 1e-9         # CDSCD for edge FET, unit "F/m^2/V"
LCDSCDEDGE = 0.0         # Length dependence of CDSCDEDGE, unit "F/m/V"
WCDSCDEDGE = 0.0         # Width dependence of CDSCDEDGE, unit "F/m/V"
PCDSCDEDGE = 0.0         # Area dependence of CDSCDEDGE, unit "F/V"
CDSCBEDGE = 0.0          # CDSCB for edge FET, unit "F/m^2/V"
LCDSCBEDGE = 0.0         # Length dependence of CDSCBEDGE, unit "F/m/V"
WCDSCBEDGE = 0.0         # Width dependence of CDSCBEDGE, unit "F/m/V"
PCDSCBEDGE = 0.0         # Area dependence of CDSCBEDGE, unit "F/V"
ETA0EDGE = 0.08          # DIBL parameter for edge FET, unit ""
LETA0EDGE = 0.0          # Length dependence of ETA0EDGE, unit "m"
WETA0EDGE = 0.0          # Width dependence of ETA0EDGE, unit "m"
PETA0EDGE = 0.0          # Area dependence of ETA0EDGE, unit "m^2"
ETABEDGE = -0.07         # ETAB for edge FET, unit "1/V"
LETABEDGE = 0.0          # Length dependence of ETABEDGE, unit "m/V"
WETABEDGE = 0.0          # Width dependence of ETABEDGE, unit "m/V"
PETABEDGE = 0.0          # Area dependence of ETABEDGE, unit "m^2/V"
KT1EDGE = -0.11          # Temperature dependence parameter of threshold voltage for edge FET, unit "V"
LKT1EDGE = 0.0           # Length dependence of KT1EDGE, unit "V*m"
WKT1EDGE = 0.0           # Width dependence of KT1EDGE, unit "V*m"
PKT1EDGE = 0.0           # Area dependence of KT1EDGE, unit "V*m^2"
KT1LEDGE = 0.0           # Temperature dependence parameter of threshold voltage for edge FET, unit "V*m"
LKT1LEDGE = 0.0          # Length dependence of KT1LEDGE, unit "V*m^2"
WKT1LEDGE = 0.0          # Width dependence of KT1LEDGE, unit "V*m^2"
PKT1LEDGE = 0.0          # Area dependence of KT1LEDGE, unit "V*m^3"
KT2EDGE = 0.022          # Temperature dependence parameter of threshold voltage for edge FET, unit ""
LKT2EDGE = 0.0           # Length dependence of KT2EDGE, unit "m"
WKT2EDGE = 0.0           # Width dependence of KT2EDGE, unit "m"
PKT2EDGE = 0.0           # Area dependence of KT2EDGE, unit "m^2"
KT1EXPEDGE = 1.0         # Temperature dependence parameter of threshold voltage for edge device, unit ""
LKT1EXPEDGE = 0.0        # Length dependence of KT1EXPEDGE, unit "m"
WKT1EXPEDGE = 0.0        # Width dependence of KT1EXPEDGE, unit "m"
PKT1EXPEDGE = 0.0        # Area dependence of KT1EXPEDGE, unit "m^2"
TNFACTOREDGE = 0.0       # Temperature dependence parameter of subthreshold slope factor for edge, unit ""
LTNFACTOREDGE = 0.0      # Length dependence of TNFACTOREDGE, unit "m"
WTNFACTOREDGE = 0.0      # Width dependence of TNFACTOREDGE, unit "m"
PTNFACTOREDGE = 0.0      # Area dependence of TNFACTOREDGE, unit "m^2"
TETA0EDGE = 0.0          # Temperature dependence parameter of DIBL parameter for edge FET, unit ""
LTETA0EDGE = 0.0         # Length dependence of TETA0EDGE, unit "m"
WTETA0EDGE = 0.0         # Width dependence of TETA0EDGE, unit "m"
PTETA0EDGE = 0.0         # Area dependence of TETA0EDGE, unit "m^2"
DVT0EDGE = 2.2           # First coefficient of SCE effect on Vth for Edge FET, unit ""
DVT1EDGE = 0.53          # Second coefficient of SCE effect on Vth for Edge FET, unit ""
DVT2EDGE = 0.0           # Body-bias coefficient for SCE effect for Edge FET, unit "1/V"
K2EDGE = 0.0             # Vth shift due to Vertical Non-uniform doping, unit "V"
LK2EDGE = 0.0            # Length dependence of K2EDGE, unit "m"
WK2EDGE = 0.0            # Width dependence of K2EDGE, unit "m"
PK2EDGE = 0.0            # Area dependence of K2EDGE, unit "m^2"
KVTH0EDGE = 0.0          # Threshold Shift parameter for stress effect, unit "V*m"
LKVTH0EDGE = 0.0         # Length dependence of KVTH0EDGE, unit "m^LLODKU0"
WKVTH0EDGE = 0.0         # Width dependence of KVTH0EDGE, unit "m^WLODKU0"
PKVTH0EDGE = 0.0         # Area dependence of KVTH0EDGE, unit "m^(LLODKU0+WLODKU0)"
STK2EDGE = 0.0           # K2 shift factor related to Vth change, unit "m"
LSTK2EDGE = 0.0          # Length dependence of STK2EDGE, unit "m^2"
WSTK2EDGE = 0.0          # Width dependence of STK2EDGE, unit "m^2"
PSTK2EDGE = 0.0          # Area dependence of STK2EDGE, unit "m^3"
STETA0EDGE = 0.0         # ETA0 shift related to Vth0 change, unit "m"
LSTETA0EDGE = 0.0        # Length dependence of STETA0EDGE, unit "m^2"
WSTETA0EDGE = 0.0        # Width dependence of STETA0EDGE, unit "m^2"
PSTETA0EDGE = 0.0        # Area dependence of STETA0EDGE, unit "m^3"
IGCLAMP = 1              # Model flag for Ig clamping, range (0, 1), unit 
LP = 1                  # Model flag for Ig clamping, unit 
RNOIK = 0.0              # Exponential coefficient for enhanced correlated thermal noise, unit ""
TNOIK = 0.0              # Empirical parameter for Leff trend of Sid at low Ids, range (-inf, inf), unit "1/m"
TNOIK2 = 0.1             # Empirical parameter for sensitivity of RNOIK, unit "1/m"
K0 = 0.0                 # Non-saturation effect parameter for strong inversion region, unit ""
LK0 = 0.0                # Length dependence of K0, unit "m"
WK0 = 0.0                # Width dependence of K0, unit "m"
PK0 = 0.0                # Area dependence of K0, unit "m^2"
K01 = 0.0                # Temperature coefficient for K0, unit "1/K"
LK01 = 0.0               # Length dependence of K0, unit "m/K"
WK01 = 0.0               # Width dependence of K0, unit "m/K"
PK01 = 0.0               # Area dependence of K0, unit "m^2/K"
M0 = 1.0                 # offset of non-saturation effect parameter for strong inversion region, unit ""
LM0 = 0.0                # Length dependence of M0, unit "m"
WM0 = 0.0                # Width dependence of M0, unit "m"
PM0 = 0.0                # Area dependence of M0, unit "m^2"
M01 = 0.0                # Temperature coefficient for M0, unit "1/K"
LM01 = 0.0               # Length dependence of M01, unit "m/K"
WM01 = 0.0               # Width dependence of M01, unit "m/K"
PM01 = 0.0               # Area dependence of M01, unit "m^2/K"

# Flicker noise model parameter for EDGE FET transistor
NEDGE = 0.0             # Area dependence of M01, unit "m^2/K"
NOIA1_EDGE = 0.0         # Flicker noise fitting parameter in strong inversionfor edge fet transitor, unit ""
NOIAX_EDGE = 0.0        # Flicker noise fitting parameter in strong inversionfor edge fet transitor, unit ""


# Flicker noise model parameter for Halo transistor
FNOIMOD = 0              # Flicker noise model selector, range (0, 1), unit 
LH = 1.0e-8              # Length of halo transistor, range (0.0, L), unit "m"
NOIA2 = NOIA             # Flicker noise parameter A for Halo, unit "s^(1-EF)/(eV)^1/m^3"
HNDEP = NOIA            # Flicker noise parameter A for Halo, unit "s^(1-EF)/(eV)^1/m^3"

# Flexibility of tuning Cgg in strong inversion
ABULK = 1.0              # For flexibility of tuning Cgg in strong inversion, range (1, 2.0), unit ""

# To enhance the fitting flexiblity for the gm/Id
C0 = 0.0                 # Lateral NUD1 voltage parameter, unit "V"
LC0 = 0.0                # Length dependence of C0, unit "V*m"
WC0 = 0.0                # Width dependence of C0, unit "V*m"
PC0 = 0.0                # Area dependence of C0, unit "V*m^2"
C01 = 0.0                # Temperature dependence of lateral NUD1 voltage parameter, unit "1/K"
LC01 = 0.0               # Length dependence of C01, unit "m/K"
WC01 = 0.0               # Width dependence of C01, unit "m/K"
PC01 = 0.0               # Area dependence of C01, unit "m^2/K"
C0SI = 1.0               # Correction factor for strong inversion used in Mnud1. After binning it should be within (0 : inf), unit "V"
LC0SI = 0.0              # Length dependence of C0SI, unit "V*m"
WC0SI = 0.0              # Width dependence of C0SI, unit "V*m"
PC0SI = 0.0              # Area dependence of C0SI, unit "V*m^2"
C0SI1 = 0.0              # Temperature dependence of C0SI1, unit "1/K"
LC0SI1 = 0.0             # Length dependence of C0SI1, unit "m/K"
WC0SI1 = 0.0             # Width dependence of C0SI1, unit "m/K"
PC0SI1 = 0.0             # Area dependence of C0SI1, unit "m^2/K"
C0SISAT = 0.0            # Correction factor for strong inversion used in Mnud1, unit "V"
LC0SISAT = 0.0           # Length dependence of C0SISAT, unit "V*m"
WC0SISAT = 0.0           # Width dependence of C0SISAT, unit "V*m"
PC0SISAT = 0.0           # Area dependence of C0SISAT, unit "V*m^2"
C0SISAT1 = 0.0           # Temperature dependence of C0SISAT1, unit "1/K"
LC0SISAT1 = 0.0          # Length dependence of C0SISAT1, unit "m/K"
WC0SISAT1 = 0.0          # Width dependence of C0SISAT1, unit "m/K"
PC0SISAT1 = 0.0          # Area dependence of C0SISAT1, unit "m^2/K"

# Minimum resistance value
minr = $simparam("minr"1m)   # Area dependence of C0SISAT1, unit "m^2/K"
# High Voltage Model Parameters

# --- Mod selectors -----
HVMOD = 0                # High Voltage series resistance model, 0: Turn Off 1: Turn On, range (0, 1), unit 
HVCAP = 0                # High Voltage capacitance model. 0: Turn Off 1: Turn On, range (0, 1), unit 
HVCAPS = 0               # High Voltage capacitance model at source side. 0: Turn Off 1: Turn On, range (0, 1), unit 
IIMOD = 0                # Flag for impact ionization in the drift region 0: Turn-Off,  1: Turn On, range (0, 1), unit 

# --- Other parameters -----
NDRIFTD = 0             # Flag for impact ionization in the drift region 0: Turn-Off,  1: Turn On, unit 
`MPRoc( VDRIFT         ,1.0e5           ,"m/sec"        ,0           ,inf        ,"Saturation velocity in the drift region" )
`MPRoc( MDRIFT         ,1.0             ,""             ,0           ,inf        ,"Non-linear resistance parameter" )
NDRIFTS = 0             # Flag for impact ionization in the drift region 0: Turn-Off,  1: Turn On, unit 
RDLCW = 100.0            # 'R'esistance of the 'D'rain side drift region at 'L'ow 'C'urrent, range (0, inf), unit "Ohm*m^WR"
RSLCW = 0                # 'R'esistance of the 'S'ource side drift region at 'L'ow 'C'urrent, range (0, inf), unit "Ohm*m^WR"
PDRWB = 0                # Body bias dependence of the drift region resistance, unit ""
VFBDRIFT = -1            # Flat-band voltage of the drift region, unit "V"
VFBOV = -1               # Flat-band voltage of the overlap region, unit "V"
LOVER = 500n             # Overlap region length, unit "m"
LOVERACC = LOVER         # Drift region length, unit "m"
NDR = NDEP               # Drift region doping, unit "m^3"
SLHV = 0                 # Parameter and Flag for controlling slope of accumulation region capacitance. 0: Turn-Off,  1: Turn On, unit ""
SLHV1 = 0               # Parameter and Flag for controlling slope of accumulation region capacitance. 0: Turn-Off,  1: Turn On, unit ""
ALPHADR = ALPHA0         # First parameter of Iii in the drift region, unit ""
BETADR = BETA0           # Second parameter of Iii in the drift region, unit ""
PRTHV = 0.0              # Temperature coefficient for drift resistance, unit ""
ATHV = 0                 # Temperature coefficient for drift region saturation velocity, unit "m/s"
HVFACTOR = 1e-3          # , range (1e-4, 1), unit ""
DRII1 = 1.0              # Parameter for carrier concentration for Impact Ionization in the the drift, unit ""
DRII2 = 5                # Saturation voltage ~ Esat * L, unit "V"
DELTAII = 0.5            # Smoothing parameter, unit "V"
